name: Manual Deploy

on: 
  workflow_dispatch:
    inputs:
      env: 
        description: "Select the target environment"
        type: choice
        required: true
        options:
          - dev
          - uat

jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment: ${{ inputs.env }}

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to selected environment
        run: |
          echo "Deploying to ${{ vars.ENV }} environment..."
          echo "API_TOKEN is ${{ secrets.API_TOKEN }}"